### ISSUE TITLE
Broken docker images in release

### ISSUE THREAD

**Issue by ajatprabha** [gojek/darkroom#43]
##### Environment

```
Installation method: Docker
Darkroom version: >= v0.0.5
Operating system: Ubuntu x86_64
Go version ('go version' output): go version go1.12.9 linux/amd64
```

##### Steps to reproduce
```
docker pull gojektech/darkroom:v0.0.9
docker run -p 3000:3000 --env-file <path-to-darkroom.env> gojektech/darkroom:v0.0.9
```

##### Observed result
```
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

##### Expected result
The server should run without errors.

##### Comments
This has most probably resulted from `CGO_ENABLED` build pipeline.

**Comment by kanisiuskenneth** [comment]
The problem exists because the build result cannot be executed from the docker image and resulting in not found. This happened because of the binary still need to use some library from the OS which the Busybox does not provide.

Disabling the `CGO_Enabled` probably will fail the build, as the WebP library that being used use the C library. Another approach to fix this issue is by releasing the binary with static library.

**Comment by ajatprabha** [comment]
Yes, I also think the issue is with linking the library. I'll have to look deeper into the issue once I get time for this. Feel free to dig deeper and fix this, I'll keep your comment in mind while looking too. ✌️
